"""empty message

Revision ID: 49eeb2c5f98d
Revises: 
Create Date: 2022-12-29 19:46:53.628810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49eeb2c5f98d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('storeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storeId'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('storeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storeId'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('itemtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemId', sa.Integer(), nullable=True),
    sa.Column('tagId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['itemId'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tagId'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemtag')
    op.drop_table('tags')
    op.drop_table('items')
    op.drop_table('user_model')
    op.drop_table('stores')
    # ### end Alembic commands ###
